version: '3.8'

services:
  actual-email-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: actual_email_scraper
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8899:8000"
    networks:
      - actual_network

networks:
  actual_network:
    external: true
